<?php
/**
 * @file
 * uconn_display_features.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function uconn_display_features_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-american-school-for-the-dea_about--:node/60.
  $menu_links['menu-american-school-for-the-dea_about--:node/60'] = array(
    'menu_name' => 'menu-american-school-for-the-dea',
    'link_path' => 'node/60',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-american-school-for-the-dea_about--:node/60',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-avon-free-public-library-co_about-:node/48.
  $menu_links['menu-avon-free-public-library-co_about-:node/48'] = array(
    'menu_name' => 'menu-avon-free-public-library-co',
    'link_path' => 'node/48',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-avon-free-public-library-co_about-:node/48',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-avon-free-public-library-co_avon-free-public-library-collections-:https://ctdigitalarchive.org/islandora/object/150002:001.
  $menu_links['menu-avon-free-public-library-co_avon-free-public-library-collections-:https://ctdigitalarchive.org/islandora/object/150002:001'] = array(
    'menu_name' => 'menu-avon-free-public-library-co',
    'link_path' => 'https://ctdigitalarchive.org/islandora/object/150002:001',
    'router_path' => '',
    'link_title' => 'Avon Free Public Library Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-avon-free-public-library-co_avon-free-public-library-collections-:https://ctdigitalarchive.org/islandora/object/150002:001',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-barnum-museum-contextual-me_about--:node/50.
  $menu_links['menu-barnum-museum-contextual-me_about--:node/50'] = array(
    'menu_name' => 'menu-barnum-museum-contextual-me',
    'link_path' => 'node/50',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-barnum-museum-contextual-me_about--:node/50',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-barnum-museum-social-media_facebook:http://www.facebook.com.
  $menu_links['menu-barnum-museum-social-media_facebook:http://www.facebook.com'] = array(
    'menu_name' => 'menu-barnum-museum-social-media',
    'link_path' => 'http://www.facebook.com',
    'router_path' => '',
    'link_title' => 'Facebook',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'facebook-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-barnum-museum-social-media_facebook:http://www.facebook.com',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-barnum-museum-social-media_twitter:http://www.twitter.com.
  $menu_links['menu-barnum-museum-social-media_twitter:http://www.twitter.com'] = array(
    'menu_name' => 'menu-barnum-museum-social-media',
    'link_path' => 'http://www.twitter.com',
    'router_path' => '',
    'link_title' => 'Twitter',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'twitter-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-barnum-museum-social-media_twitter:http://www.twitter.com',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-bethel-public-library-conte_about-:node/39.
  $menu_links['menu-bethel-public-library-conte_about-:node/39'] = array(
    'menu_name' => 'menu-bethel-public-library-conte',
    'link_path' => 'node/39',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-bethel-public-library-conte_about-:node/39',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-bethel-public-library-conte_bethel-public-library-collections-:islandora/object/140006:Bethel.
  $menu_links['menu-bethel-public-library-conte_bethel-public-library-collections-:islandora/object/140006:Bethel'] = array(
    'menu_name' => 'menu-bethel-public-library-conte',
    'link_path' => 'islandora/object/140006:Bethel',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bethel Public Library Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-bethel-public-library-conte_bethel-public-library-collections-:islandora/object/140006:Bethel',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-bethel-public-library-conte_bibliomation-collections-:http://collections.ctdigitalarchive.org/islandora/object/140002%3ABiblio.
  $menu_links['menu-bethel-public-library-conte_bibliomation-collections-:http://collections.ctdigitalarchive.org/islandora/object/140002%3ABiblio'] = array(
    'menu_name' => 'menu-bethel-public-library-conte',
    'link_path' => 'http://collections.ctdigitalarchive.org/islandora/object/140002%3ABiblio',
    'router_path' => '',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'identifier' => 'menu-bethel-public-library-conte_bibliomation-collections-:http://collections.ctdigitalarchive.org/islandora/object/140002%3ABiblio',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-bethel-public-library-conte_website:http://www.bethellibrary.org/.
  $menu_links['menu-bethel-public-library-conte_website:http://www.bethellibrary.org/'] = array(
    'menu_name' => 'menu-bethel-public-library-conte',
    'link_path' => 'http://www.bethellibrary.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'identifier' => 'menu-bethel-public-library-conte_website:http://www.bethellibrary.org/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-biblio-social-media-menu_facebook:http://www.facebook.com.
  $menu_links['menu-biblio-social-media-menu_facebook:http://www.facebook.com'] = array(
    'menu_name' => 'menu-biblio-social-media-menu',
    'link_path' => 'http://www.facebook.com',
    'router_path' => '',
    'link_title' => 'Facebook',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'facebook-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-biblio-social-media-menu_facebook:http://www.facebook.com',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-biblio-test-contextual-menu_about-:node/95.
  $menu_links['menu-biblio-test-contextual-menu_about-:node/95'] = array(
    'menu_name' => 'menu-biblio-test-contextual-menu',
    'link_path' => 'node/95',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-biblio-test-contextual-menu_about-:node/95',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-biblio-test-contextual-menu_bibliomation:http://www.biblio.org.
  $menu_links['menu-biblio-test-contextual-menu_bibliomation:http://www.biblio.org'] = array(
    'menu_name' => 'menu-biblio-test-contextual-menu',
    'link_path' => 'http://www.biblio.org',
    'router_path' => '',
    'link_title' => 'Bibliomation',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-biblio-test-contextual-menu_bibliomation:http://www.biblio.org',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-bibliomation-contextual-men_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-bibliomation-contextual-men_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-bibliomation-contextual-men',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-bibliomation-contextual-men_bibliomation-collections-:islandora/object/140002:Biblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-bill-memorial-library-conte_about-:node/53.
  $menu_links['menu-bill-memorial-library-conte_about-:node/53'] = array(
    'menu_name' => 'menu-bill-memorial-library-conte',
    'link_path' => 'node/53',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-bill-memorial-library-conte_about-:node/53',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-bill-memorial-library-conte_bill-memorial-library-collections-:islandora/object/350002:BillMemorialLibrary.
  $menu_links['menu-bill-memorial-library-conte_bill-memorial-library-collections-:islandora/object/350002:BillMemorialLibrary'] = array(
    'menu_name' => 'menu-bill-memorial-library-conte',
    'link_path' => 'islandora/object/350002:BillMemorialLibrary',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bill Memorial Library Collections |',
    'options' => array(
      'identifier' => 'menu-bill-memorial-library-conte_bill-memorial-library-collections-:islandora/object/350002:BillMemorialLibrary',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-bridgeport-history-center-c_about-:node/83.
  $menu_links['menu-bridgeport-history-center-c_about-:node/83'] = array(
    'menu_name' => 'menu-bridgeport-history-center-c',
    'link_path' => 'node/83',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-bridgeport-history-center-c_about-:node/83',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-bridgeport-history-center-c_bridgeport-history-center-collections-:islandora/object/110002:Admin001.
  $menu_links['menu-bridgeport-history-center-c_bridgeport-history-center-collections-:islandora/object/110002:Admin001'] = array(
    'menu_name' => 'menu-bridgeport-history-center-c',
    'link_path' => 'islandora/object/110002:Admin001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bridgeport History Center Collections |',
    'options' => array(
      'identifier' => 'menu-bridgeport-history-center-c_bridgeport-history-center-collections-:islandora/object/110002:Admin001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-content_bibliomation:http://hdl.handle.net/11134/140002%3ABiblio.
  $menu_links['menu-browse-content_bibliomation:http://hdl.handle.net/11134/140002%3ABiblio'] = array(
    'menu_name' => 'menu-browse-content',
    'link_path' => 'http://hdl.handle.net/11134/140002%3ABiblio',
    'router_path' => '',
    'link_title' => 'Bibliomation',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-browse-content_bibliomation:http://hdl.handle.net/11134/140002%3ABiblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-browse-content_root-collection:islandora.
  $menu_links['menu-browse-content_root-collection:islandora'] = array(
    'menu_name' => 'menu-browse-content',
    'link_path' => 'islandora',
    'router_path' => 'islandora',
    'link_title' => 'Root Collection',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-browse-content_root-collection:islandora',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-cahsl-contextual-menu_about-:node/76.
  $menu_links['menu-cahsl-contextual-menu_about-:node/76'] = array(
    'menu_name' => 'menu-cahsl-contextual-menu',
    'link_path' => 'node/76',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-cahsl-contextual-menu_about-:node/76',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-cahsl-contextual-menu_website:https://nahsl.libguides.com/cahsl.
  $menu_links['menu-cahsl-contextual-menu_website:https://nahsl.libguides.com/cahsl'] = array(
    'menu_name' => 'menu-cahsl-contextual-menu',
    'link_path' => 'https://nahsl.libguides.com/cahsl',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'identifier' => 'menu-cahsl-contextual-menu_website:https://nahsl.libguides.com/cahsl',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-case-memorial-library-conte_about-:node/81.
  $menu_links['menu-case-memorial-library-conte_about-:node/81'] = array(
    'menu_name' => 'menu-case-memorial-library-conte',
    'link_path' => 'node/81',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-case-memorial-library-conte_about-:node/81',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-contextual_about-:node/96.
  $menu_links['menu-ch-booth-library-contextual_about-:node/96'] = array(
    'menu_name' => 'menu-ch-booth-library-contextual',
    'link_path' => 'node/96',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-contextual_about-:node/96',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-contextual_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-ch-booth-library-contextual_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-ch-booth-library-contextual',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-contextual_bibliomation-collections-:islandora/object/140002:Biblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-contextual_ch-booth-collections-:islandora/object/140008:CHBooth.
  $menu_links['menu-ch-booth-library-contextual_ch-booth-collections-:islandora/object/140008:CHBooth'] = array(
    'menu_name' => 'menu-ch-booth-library-contextual',
    'link_path' => 'islandora/object/140008:CHBooth',
    'router_path' => 'islandora/object/%',
    'link_title' => 'C.H. Booth Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-contextual_ch-booth-collections-:islandora/object/140008:CHBooth',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-contextual_website:https://www.chboothlibrary.org/.
  $menu_links['menu-ch-booth-library-contextual_website:https://www.chboothlibrary.org/'] = array(
    'menu_name' => 'menu-ch-booth-library-contextual',
    'link_path' => 'https://www.chboothlibrary.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-contextual_website:https://www.chboothlibrary.org/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-social-med_facebook:https://www.facebook.com/chboothlibrary/.
  $menu_links['menu-ch-booth-library-social-med_facebook:https://www.facebook.com/chboothlibrary/'] = array(
    'menu_name' => 'menu-ch-booth-library-social-med',
    'link_path' => 'https://www.facebook.com/chboothlibrary/',
    'router_path' => '',
    'link_title' => 'Facebook',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'facebook-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-social-med_facebook:https://www.facebook.com/chboothlibrary/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-social-med_instagram:https://www.instagram.com/chboothlibrary/.
  $menu_links['menu-ch-booth-library-social-med_instagram:https://www.instagram.com/chboothlibrary/'] = array(
    'menu_name' => 'menu-ch-booth-library-social-med',
    'link_path' => 'https://www.instagram.com/chboothlibrary/',
    'router_path' => '',
    'link_title' => 'Instagram',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'instagram-1',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-social-med_instagram:https://www.instagram.com/chboothlibrary/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-ch-booth-library-social-med_twitter:https://twitter.com/CHBoothLibrary.
  $menu_links['menu-ch-booth-library-social-med_twitter:https://twitter.com/CHBoothLibrary'] = array(
    'menu_name' => 'menu-ch-booth-library-social-med',
    'link_path' => 'https://twitter.com/CHBoothLibrary',
    'router_path' => '',
    'link_title' => 'Twitter',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'twitter-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ch-booth-library-social-med_twitter:https://twitter.com/CHBoothLibrary',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-chi-contextual-menu_about--:node/36.
  $menu_links['menu-chi-contextual-menu_about--:node/36'] = array(
    'menu_name' => 'menu-chi-contextual-menu',
    'link_path' => 'node/36',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-chi-contextual-menu_about--:node/36',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-chs-contextual-menu_about--:node/62.
  $menu_links['menu-chs-contextual-menu_about--:node/62'] = array(
    'menu_name' => 'menu-chs-contextual-menu',
    'link_path' => 'node/62',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-chs-contextual-menu_about--:node/62',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-connecticut-college-context_about-:node/70.
  $menu_links['menu-connecticut-college-context_about-:node/70'] = array(
    'menu_name' => 'menu-connecticut-college-context',
    'link_path' => 'node/70',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-connecticut-college-context_about-:node/70',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-connecticut-college-context_connecticut-college-collections-:islandora/object/490002:ConnCollege.
  $menu_links['menu-connecticut-college-context_connecticut-college-collections-:islandora/object/490002:ConnCollege'] = array(
    'menu_name' => 'menu-connecticut-college-context',
    'link_path' => 'islandora/object/490002:ConnCollege',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Connecticut College Collections |',
    'options' => array(
      'identifier' => 'menu-connecticut-college-context_connecticut-college-collections-:islandora/object/490002:ConnCollege',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-connecticut-landmarks-conte_about--:node/72.
  $menu_links['menu-connecticut-landmarks-conte_about--:node/72'] = array(
    'menu_name' => 'menu-connecticut-landmarks-conte',
    'link_path' => 'node/72',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-connecticut-landmarks-conte_about--:node/72',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-connecticut-landmarks-conte_ct-landmarks-collections-:islandora/object/370002:CTLandmarksJME.
  $menu_links['menu-connecticut-landmarks-conte_ct-landmarks-collections-:islandora/object/370002:CTLandmarksJME'] = array(
    'menu_name' => 'menu-connecticut-landmarks-conte',
    'link_path' => 'islandora/object/370002:CTLandmarksJME',
    'router_path' => 'islandora/object/%',
    'link_title' => 'CT Landmarks Collections |',
    'options' => array(
      'identifier' => 'menu-connecticut-landmarks-conte_ct-landmarks-collections-:islandora/object/370002:CTLandmarksJME',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-connecticut-state-library-c_about-:node/34.
  $menu_links['menu-connecticut-state-library-c_about-:node/34'] = array(
    'menu_name' => 'menu-connecticut-state-library-c',
    'link_path' => 'node/34',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'identifier' => 'menu-connecticut-state-library-c_about-:node/34',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-csl-contextual-menu_about:node/34.
  $menu_links['menu-csl-contextual-menu_about:node/34'] = array(
    'menu_name' => 'menu-csl-contextual-menu',
    'link_path' => 'node/34',
    'router_path' => 'node/%',
    'link_title' => 'About',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-csl-contextual-menu_about:node/34',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-csl-contextual-menu_home:islandora/object/30002:csl.
  $menu_links['menu-csl-contextual-menu_home:islandora/object/30002:csl'] = array(
    'menu_name' => 'menu-csl-contextual-menu',
    'link_path' => 'islandora/object/30002:csl',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Home',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-csl-contextual-menu_home:islandora/object/30002:csl',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-csmnh-contextual-menu_about--:node/51.
  $menu_links['menu-csmnh-contextual-menu_about--:node/51'] = array(
    'menu_name' => 'menu-csmnh-contextual-menu',
    'link_path' => 'node/51',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-csmnh-contextual-menu_about--:node/51',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-csmnh-contextual-menu_csmnh-collections-:islandora/object/20006:CTSMNH.
  $menu_links['menu-csmnh-contextual-menu_csmnh-collections-:islandora/object/20006:CTSMNH'] = array(
    'menu_name' => 'menu-csmnh-contextual-menu',
    'link_path' => 'islandora/object/20006:CTSMNH',
    'router_path' => 'islandora/object/%',
    'link_title' => 'CSMNH Collections |',
    'options' => array(
      'identifier' => 'menu-csmnh-contextual-menu_csmnh-collections-:islandora/object/20006:CTSMNH',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive.
  $menu_links['menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    'router_path' => '',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_about-:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members.
  $menu_links['menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members',
    'router_path' => '',
    'link_title' => 'Community Members | ',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_community-members--:https://confluence.uits.uconn.edu/confluence/display/CTDA/Community+Members',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology.
  $menu_links['menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology',
    'router_path' => '',
    'link_title' => 'CTDA Technology |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_ctda-technology-:https://confluence.uits.uconn.edu/confluence/display/CTDA/CTDA+Technology',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -4,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA.
  $menu_links['menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA',
    'router_path' => '',
    'link_title' => 'Join',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_join:https://confluence.uits.uconn.edu/confluence/display/CTDA/Join+the+CTDA',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -2,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA.
  $menu_links['menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA'] = array(
    'menu_name' => 'menu-ctda-contextual-menu',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA',
    'router_path' => '',
    'link_title' => 'People of CTDA |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-contextual-menu_people-of-ctda-:https://confluence.uits.uconn.edu/confluence/display/CTDA/People+of+CTDA',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -6,
    'customized' => 1,
  );
  // Exported menu link: menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive.
  $menu_links['menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive'] = array(
    'menu_name' => 'menu-ctda-information',
    'link_path' => 'https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    'router_path' => '',
    'link_title' => 'About the CTDA',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-ctda-information_about-the-ctda:https://confluence.uits.uconn.edu/confluence/display/CTDA/About+the+Connecticut+Digital+Archive',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-c_about-:node/93.
  $menu_links['menu-deep-river-public-library-c_about-:node/93'] = array(
    'menu_name' => 'menu-deep-river-public-library-c',
    'link_path' => 'node/93',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-c_about-:node/93',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-c_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-deep-river-public-library-c_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-deep-river-public-library-c',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-c_bibliomation-collections-:islandora/object/140002:Biblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-c_contact:mailto:deepriverpubliclibrary@gmail.com.
  $menu_links['menu-deep-river-public-library-c_contact:mailto:deepriverpubliclibrary@gmail.com'] = array(
    'menu_name' => 'menu-deep-river-public-library-c',
    'link_path' => 'mailto:deepriverpubliclibrary@gmail.com',
    'router_path' => '',
    'link_title' => 'Contact',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-c_contact:mailto:deepriverpubliclibrary@gmail.com',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-c_deep-river-public-library-collections-:islandora/object/140066:DeepRiver.
  $menu_links['menu-deep-river-public-library-c_deep-river-public-library-collections-:islandora/object/140066:DeepRiver'] = array(
    'menu_name' => 'menu-deep-river-public-library-c',
    'link_path' => 'islandora/object/140066:DeepRiver',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Deep River Public Library Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-c_deep-river-public-library-collections-:islandora/object/140066:DeepRiver',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-c_website-:http://deepriverlibrary.accountsupport.com/.
  $menu_links['menu-deep-river-public-library-c_website-:http://deepriverlibrary.accountsupport.com/'] = array(
    'menu_name' => 'menu-deep-river-public-library-c',
    'link_path' => 'http://deepriverlibrary.accountsupport.com/',
    'router_path' => '',
    'link_title' => 'Website |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-c_website-:http://deepriverlibrary.accountsupport.com/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-deep-river-public-library-s_facebook:https://www.facebook.com/Deep-River-Public-Library-312574775774/.
  $menu_links['menu-deep-river-public-library-s_facebook:https://www.facebook.com/Deep-River-Public-Library-312574775774/'] = array(
    'menu_name' => 'menu-deep-river-public-library-s',
    'link_path' => 'https://www.facebook.com/Deep-River-Public-Library-312574775774/',
    'router_path' => '',
    'link_title' => 'Facebook',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'facebook-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-deep-river-public-library-s_facebook:https://www.facebook.com/Deep-River-Public-Library-312574775774/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-default-institution-context_home--:http://ctda-staging1.lib.uconn.edu/islandora/object/Islandora%3Agreg.
  $menu_links['menu-default-institution-context_home--:http://ctda-staging1.lib.uconn.edu/islandora/object/Islandora%3Agreg'] = array(
    'menu_name' => 'menu-default-institution-context',
    'link_path' => 'http://ctda-staging1.lib.uconn.edu/islandora/object/Islandora%3Agreg',
    'router_path' => '',
    'link_title' => 'Home | ',
    'options' => array(
      'identifier' => 'menu-default-institution-context_home--:http://ctda-staging1.lib.uconn.edu/islandora/object/Islandora%3Agreg',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-contex_about-:node/88.
  $menu_links['menu-derby-public-library-contex_about-:node/88'] = array(
    'menu_name' => 'menu-derby-public-library-contex',
    'link_path' => 'node/88',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-contex_about-:node/88',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-contex_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-derby-public-library-contex_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-derby-public-library-contex',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-contex_bibliomation-collections-:islandora/object/140002:Biblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-contex_derby-public-library-collection-:islandora/object/140011:Derby.
  $menu_links['menu-derby-public-library-contex_derby-public-library-collection-:islandora/object/140011:Derby'] = array(
    'menu_name' => 'menu-derby-public-library-contex',
    'link_path' => 'islandora/object/140011:Derby',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Derby Public Library Collection |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-contex_derby-public-library-collection-:islandora/object/140011:Derby',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-contex_website:http://derbypubliclibrary.org/.
  $menu_links['menu-derby-public-library-contex_website:http://derbypubliclibrary.org/'] = array(
    'menu_name' => 'menu-derby-public-library-contex',
    'link_path' => 'http://derbypubliclibrary.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-contex_website:http://derbypubliclibrary.org/',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-social_facebook:https://www.facebook.com/DerbyPublicLibrary?ref=hl.
  $menu_links['menu-derby-public-library-social_facebook:https://www.facebook.com/DerbyPublicLibrary?ref=hl'] = array(
    'menu_name' => 'menu-derby-public-library-social',
    'link_path' => 'https://www.facebook.com/DerbyPublicLibrary?ref=hl',
    'router_path' => '',
    'link_title' => 'Facebook',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'facebook-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-social_facebook:https://www.facebook.com/DerbyPublicLibrary?ref=hl',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-derby-public-library-social_twitter:https://twitter.com/DerbyPublicLib?lang=en.
  $menu_links['menu-derby-public-library-social_twitter:https://twitter.com/DerbyPublicLib?lang=en'] = array(
    'menu_name' => 'menu-derby-public-library-social',
    'link_path' => 'https://twitter.com/DerbyPublicLib?lang=en',
    'router_path' => '',
    'link_title' => 'Twitter',
    'options' => array(
      'icon' => array(
        'bundle' => 'dgi_default_bundle',
        'icon' => 'twitter-squared',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_replace',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-derby-public-library-social_twitter:https://twitter.com/DerbyPublicLib?lang=en',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-enfield-public-library-cont_about-:node/49.
  $menu_links['menu-enfield-public-library-cont_about-:node/49'] = array(
    'menu_name' => 'menu-enfield-public-library-cont',
    'link_path' => 'node/49',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-enfield-public-library-cont_about-:node/49',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-enfield-public-library-cont_enfield-public-library-collections-:islandora/object/430002:EnfieldPublic.
  $menu_links['menu-enfield-public-library-cont_enfield-public-library-collections-:islandora/object/430002:EnfieldPublic'] = array(
    'menu_name' => 'menu-enfield-public-library-cont',
    'link_path' => 'islandora/object/430002:EnfieldPublic',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Enfield Public Library Collections |',
    'options' => array(
      'identifier' => 'menu-enfield-public-library-cont_enfield-public-library-collections-:islandora/object/430002:EnfieldPublic',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-fairfield-museum-contextual_about--:node/78.
  $menu_links['menu-fairfield-museum-contextual_about--:node/78'] = array(
    'menu_name' => 'menu-fairfield-museum-contextual',
    'link_path' => 'node/78',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-fairfield-museum-contextual_about--:node/78',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-fairfield-museum-contextual_fairfield-museum-and-history-center-collections-:https://ctdigitalarchive.org/islandora/object/80002:001.
  $menu_links['menu-fairfield-museum-contextual_fairfield-museum-and-history-center-collections-:https://ctdigitalarchive.org/islandora/object/80002:001'] = array(
    'menu_name' => 'menu-fairfield-museum-contextual',
    'link_path' => 'https://ctdigitalarchive.org/islandora/object/80002:001',
    'router_path' => '',
    'link_title' => 'Fairfield Museum and History Center Collections |',
    'options' => array(
      'identifier' => 'menu-fairfield-museum-contextual_fairfield-museum-and-history-center-collections-:https://ctdigitalarchive.org/islandora/object/80002:001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-florence-griswold-museum-co_about--:node/69.
  $menu_links['menu-florence-griswold-museum-co_about--:node/69'] = array(
    'menu_name' => 'menu-florence-griswold-museum-co',
    'link_path' => 'node/69',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-florence-griswold-museum-co_about--:node/69',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-footer-menu_login:user/login.
  $menu_links['menu-footer-menu_login:user/login'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'user/login',
    'router_path' => 'user/login',
    'link_title' => 'Login',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'menu-footer-menu_login:user/login',
      'alter' => TRUE,
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-groton-public-library-conte_about--:node/65.
  $menu_links['menu-groton-public-library-conte_about--:node/65'] = array(
    'menu_name' => 'menu-groton-public-library-conte',
    'link_path' => 'node/65',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-groton-public-library-conte_about--:node/65',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-hagaman-memorial-library-co_about-:node/79.
  $menu_links['menu-hagaman-memorial-library-co_about-:node/79'] = array(
    'menu_name' => 'menu-hagaman-memorial-library-co',
    'link_path' => 'node/79',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-hagaman-memorial-library-co_about-:node/79',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-hagaman-memorial-library-co_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-hagaman-memorial-library-co_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-hagaman-memorial-library-co',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-hagaman-memorial-library-co_bibliomation-collections-:islandora/object/140002:Biblio',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-hagaman-memorial-library-co_contact:https://www.hagamanlibrary.org/staff-contacts/.
  $menu_links['menu-hagaman-memorial-library-co_contact:https://www.hagamanlibrary.org/staff-contacts/'] = array(
    'menu_name' => 'menu-hagaman-memorial-library-co',
    'link_path' => 'https://www.hagamanlibrary.org/staff-contacts/',
    'router_path' => '',
    'link_title' => 'Contact',
    'options' => array(
      'identifier' => 'menu-hagaman-memorial-library-co_contact:https://www.hagamanlibrary.org/staff-contacts/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: menu-hagaman-memorial-library-co_hagaman-memorial-library-collections--:islandora/object/140019:Hagaman.
  $menu_links['menu-hagaman-memorial-library-co_hagaman-memorial-library-collections--:islandora/object/140019:Hagaman'] = array(
    'menu_name' => 'menu-hagaman-memorial-library-co',
    'link_path' => 'islandora/object/140019:Hagaman',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Hagaman Memorial Library Collections | ',
    'options' => array(
      'identifier' => 'menu-hagaman-memorial-library-co_hagaman-memorial-library-collections--:islandora/object/140019:Hagaman',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-hartford-medical-society-co_about--:node/73.
  $menu_links['menu-hartford-medical-society-co_about--:node/73'] = array(
    'menu_name' => 'menu-hartford-medical-society-co',
    'link_path' => 'node/73',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-hartford-medical-society-co_about--:node/73',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-hartford-medical-society-co_hartford-medical-society-collections-:islandora/object/310002:AdminJME.
  $menu_links['menu-hartford-medical-society-co_hartford-medical-society-collections-:islandora/object/310002:AdminJME'] = array(
    'menu_name' => 'menu-hartford-medical-society-co',
    'link_path' => 'islandora/object/310002:AdminJME',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Hartford Medical Society Collections |',
    'options' => array(
      'identifier' => 'menu-hartford-medical-society-co_hartford-medical-society-collections-:islandora/object/310002:AdminJME',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-hartford-public-library-men_about-:node/67.
  $menu_links['menu-hartford-public-library-men_about-:node/67'] = array(
    'menu_name' => 'menu-hartford-public-library-men',
    'link_path' => 'node/67',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-hartford-public-library-men_about-:node/67',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-hartford-public-library-men_hpl-collections--:islandora/object/50002:AdminJME02.
  $menu_links['menu-hartford-public-library-men_hpl-collections--:islandora/object/50002:AdminJME02'] = array(
    'menu_name' => 'menu-hartford-public-library-men',
    'link_path' => 'islandora/object/50002:AdminJME02',
    'router_path' => 'islandora/object/%',
    'link_title' => 'HPL Collections | ',
    'options' => array(
      'identifier' => 'menu-hartford-public-library-men_hpl-collections--:islandora/object/50002:AdminJME02',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-ivoryton-library-contextual_about--:node/64.
  $menu_links['menu-ivoryton-library-contextual_about--:node/64'] = array(
    'menu_name' => 'menu-ivoryton-library-contextual',
    'link_path' => 'node/64',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-ivoryton-library-contextual_about--:node/64',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-ivoryton-library-contextual_ivoryton-library-association-collections-:islandora/object/220002:ILA001.
  $menu_links['menu-ivoryton-library-contextual_ivoryton-library-association-collections-:islandora/object/220002:ILA001'] = array(
    'menu_name' => 'menu-ivoryton-library-contextual',
    'link_path' => 'islandora/object/220002:ILA001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Ivoryton Library Association Collections |',
    'options' => array(
      'identifier' => 'menu-ivoryton-library-contextual_ivoryton-library-association-collections-:islandora/object/220002:ILA001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-ivoryton-library-contextual_website:http://ivorytonlibrary.org/.
  $menu_links['menu-ivoryton-library-contextual_website:http://ivorytonlibrary.org/'] = array(
    'menu_name' => 'menu-ivoryton-library-contextual',
    'link_path' => 'http://ivorytonlibrary.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'identifier' => 'menu-ivoryton-library-contextual_website:http://ivorytonlibrary.org/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -3,
    'customized' => 1,
  );
  // Exported menu link: menu-kent-memorial-library-conte_about-:node/77.
  $menu_links['menu-kent-memorial-library-conte_about-:node/77'] = array(
    'menu_name' => 'menu-kent-memorial-library-conte',
    'link_path' => 'node/77',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-kent-memorial-library-conte_about-:node/77',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-kent-memorial-library-conte_bibliomation-collections-:islandora/object/140002:Biblio.
  $menu_links['menu-kent-memorial-library-conte_bibliomation-collections-:islandora/object/140002:Biblio'] = array(
    'menu_name' => 'menu-kent-memorial-library-conte',
    'link_path' => 'islandora/object/140002:Biblio',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Bibliomation Collections |',
    'options' => array(
      'identifier' => 'menu-kent-memorial-library-conte_bibliomation-collections-:islandora/object/140002:Biblio',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-kent-memorial-library-conte_kent-memorial-library-collections-:islandora/object/140026:kentSuffield.
  $menu_links['menu-kent-memorial-library-conte_kent-memorial-library-collections-:islandora/object/140026:kentSuffield'] = array(
    'menu_name' => 'menu-kent-memorial-library-conte',
    'link_path' => 'islandora/object/140026:kentSuffield',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Kent Memorial Library Collections |',
    'options' => array(
      'identifier' => 'menu-kent-memorial-library-conte_kent-memorial-library-collections-:islandora/object/140026:kentSuffield',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-kent-memorial-library-conte_website:http://www.suffield-library.org/.
  $menu_links['menu-kent-memorial-library-conte_website:http://www.suffield-library.org/'] = array(
    'menu_name' => 'menu-kent-memorial-library-conte',
    'link_path' => 'http://www.suffield-library.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'identifier' => 'menu-kent-memorial-library-conte_website:http://www.suffield-library.org/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: menu-litchfield-historical-conte_about--:node/58.
  $menu_links['menu-litchfield-historical-conte_about--:node/58'] = array(
    'menu_name' => 'menu-litchfield-historical-conte',
    'link_path' => 'node/58',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-litchfield-historical-conte_about--:node/58',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-litchfield-historical-conte_litchfield-historical-society-collections-:islandora/object/400002:LHS.
  $menu_links['menu-litchfield-historical-conte_litchfield-historical-society-collections-:islandora/object/400002:LHS'] = array(
    'menu_name' => 'menu-litchfield-historical-conte',
    'link_path' => 'islandora/object/400002:LHS',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Litchfield Historical Society Collections |',
    'options' => array(
      'identifier' => 'menu-litchfield-historical-conte_litchfield-historical-society-collections-:islandora/object/400002:LHS',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-lymen-allyn-art-museum-cont_about--:node/57.
  $menu_links['menu-lymen-allyn-art-museum-cont_about--:node/57'] = array(
    'menu_name' => 'menu-lymen-allyn-art-museum-cont',
    'link_path' => 'node/57',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-lymen-allyn-art-museum-cont_about--:node/57',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-lymen-allyn-art-museum-cont_lyman-allyn-art-museum-collections-:islandora/object/170002:LAAM001.
  $menu_links['menu-lymen-allyn-art-museum-cont_lyman-allyn-art-museum-collections-:islandora/object/170002:LAAM001'] = array(
    'menu_name' => 'menu-lymen-allyn-art-museum-cont',
    'link_path' => 'islandora/object/170002:LAAM001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Lyman Allyn Art Museum Collections |',
    'options' => array(
      'identifier' => 'menu-lymen-allyn-art-museum-cont_lyman-allyn-art-museum-collections-:islandora/object/170002:LAAM001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-lymen-allyn-art-museum-cont_website:https://www.lymanallyn.org/.
  $menu_links['menu-lymen-allyn-art-museum-cont_website:https://www.lymanallyn.org/'] = array(
    'menu_name' => 'menu-lymen-allyn-art-museum-cont',
    'link_path' => 'https://www.lymanallyn.org/',
    'router_path' => '',
    'link_title' => 'Website',
    'options' => array(
      'identifier' => 'menu-lymen-allyn-art-museum-cont_website:https://www.lymanallyn.org/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -5,
    'customized' => 1,
  );
  // Exported menu link: menu-mattatuck-museum-contextual_about-:node/74.
  $menu_links['menu-mattatuck-museum-contextual_about-:node/74'] = array(
    'menu_name' => 'menu-mattatuck-museum-contextual',
    'link_path' => 'node/74',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-mattatuck-museum-contextual_about-:node/74',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-mattatuck-museum-contextual_mattatuck-museum-collections-:islandora/object/260002:MM001.
  $menu_links['menu-mattatuck-museum-contextual_mattatuck-museum-collections-:islandora/object/260002:MM001'] = array(
    'menu_name' => 'menu-mattatuck-museum-contextual',
    'link_path' => 'islandora/object/260002:MM001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Mattatuck Museum Collections |',
    'options' => array(
      'identifier' => 'menu-mattatuck-museum-contextual_mattatuck-museum-collections-:islandora/object/260002:MM001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-mystic-arts-center-contextu_about--:node/80.
  $menu_links['menu-mystic-arts-center-contextu_about--:node/80'] = array(
    'menu_name' => 'menu-mystic-arts-center-contextu',
    'link_path' => 'node/80',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-mystic-arts-center-contextu_about--:node/80',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-mystic-arts-center-contextu_mystic-arts-museum-collections-:islandora/object/200002:MAC001.
  $menu_links['menu-mystic-arts-center-contextu_mystic-arts-museum-collections-:islandora/object/200002:MAC001'] = array(
    'menu_name' => 'menu-mystic-arts-center-contextu',
    'link_path' => 'islandora/object/200002:MAC001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Mystic Arts Museum Collections |',
    'options' => array(
      'identifier' => 'menu-mystic-arts-center-contextu_mystic-arts-museum-collections-:islandora/object/200002:MAC001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-mystic-seaport-contextual-m_about--:node/82.
  $menu_links['menu-mystic-seaport-contextual-m_about--:node/82'] = array(
    'menu_name' => 'menu-mystic-seaport-contextual-m',
    'link_path' => 'node/82',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-mystic-seaport-contextual-m_about--:node/82',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-mystic-seaport-contextual-m_mystic-seaport-collections-:islandora/object/70002:AdminJME.
  $menu_links['menu-mystic-seaport-contextual-m_mystic-seaport-collections-:islandora/object/70002:AdminJME'] = array(
    'menu_name' => 'menu-mystic-seaport-contextual-m',
    'link_path' => 'islandora/object/70002:AdminJME',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Mystic Seaport Collections |',
    'options' => array(
      'identifier' => 'menu-mystic-seaport-contextual-m_mystic-seaport-collections-:islandora/object/70002:AdminJME',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-new-britain-museum-of-ameri_about-:node/68.
  $menu_links['menu-new-britain-museum-of-ameri_about-:node/68'] = array(
    'menu_name' => 'menu-new-britain-museum-of-ameri',
    'link_path' => 'node/68',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-new-britain-museum-of-ameri_about-:node/68',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-new-britain-museum-of-ameri_nbmaa-collections--:islandora/object/210002:NBMAA.
  $menu_links['menu-new-britain-museum-of-ameri_nbmaa-collections--:islandora/object/210002:NBMAA'] = array(
    'menu_name' => 'menu-new-britain-museum-of-ameri',
    'link_path' => 'islandora/object/210002:NBMAA',
    'router_path' => 'islandora/object/%',
    'link_title' => 'NBMAA Collections | ',
    'options' => array(
      'identifier' => 'menu-new-britain-museum-of-ameri_nbmaa-collections--:islandora/object/210002:NBMAA',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-new-haven-museum-contextual_about--:node/85.
  $menu_links['menu-new-haven-museum-contextual_about--:node/85'] = array(
    'menu_name' => 'menu-new-haven-museum-contextual',
    'link_path' => 'node/85',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-new-haven-museum-contextual_about--:node/85',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-new-haven-museum-contextual_new-haven-museum-collections--:islandora/object/280002:NHM001.
  $menu_links['menu-new-haven-museum-contextual_new-haven-museum-collections--:islandora/object/280002:NHM001'] = array(
    'menu_name' => 'menu-new-haven-museum-contextual',
    'link_path' => 'islandora/object/280002:NHM001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'New Haven Museum Collections | ',
    'options' => array(
      'identifier' => 'menu-new-haven-museum-contextual_new-haven-museum-collections--:islandora/object/280002:NHM001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-norwalk-public-library-cont_about--:node/55.
  $menu_links['menu-norwalk-public-library-cont_about--:node/55'] = array(
    'menu_name' => 'menu-norwalk-public-library-cont',
    'link_path' => 'node/55',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-norwalk-public-library-cont_about--:node/55',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-norwalk-public-library-cont_norwalk-public-library-collection-:islandora/object/450002:NPL.
  $menu_links['menu-norwalk-public-library-cont_norwalk-public-library-collection-:islandora/object/450002:NPL'] = array(
    'menu_name' => 'menu-norwalk-public-library-cont',
    'link_path' => 'islandora/object/450002:NPL',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Norwalk Public Library Collection |',
    'options' => array(
      'identifier' => 'menu-norwalk-public-library-cont_norwalk-public-library-collection-:islandora/object/450002:NPL',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-pt-barnum-digital-collectio_abc-a-barnum-companion:islandora/object/60002:ptb_abarnumcompanion.
  $menu_links['menu-pt-barnum-digital-collectio_abc-a-barnum-companion:islandora/object/60002:ptb_abarnumcompanion'] = array(
    'menu_name' => 'menu-pt-barnum-digital-collectio',
    'link_path' => 'islandora/object/60002:ptb_abarnumcompanion',
    'router_path' => 'islandora/object/%',
    'link_title' => 'ABC: A Barnum Companion',
    'options' => array(
      'identifier' => 'menu-pt-barnum-digital-collectio_abc-a-barnum-companion:islandora/object/60002:ptb_abarnumcompanion',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-pt-barnum-digital-collectio_about--:node/61.
  $menu_links['menu-pt-barnum-digital-collectio_about--:node/61'] = array(
    'menu_name' => 'menu-pt-barnum-digital-collectio',
    'link_path' => 'node/61',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-pt-barnum-digital-collectio_about--:node/61',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-pt-barnum-digital-collectio_pt-barnum-digital-collection-home-:islandora/object/60002:PTBarnumDigitalCollection.
  $menu_links['menu-pt-barnum-digital-collectio_pt-barnum-digital-collection-home-:islandora/object/60002:PTBarnumDigitalCollection'] = array(
    'menu_name' => 'menu-pt-barnum-digital-collectio',
    'link_path' => 'islandora/object/60002:PTBarnumDigitalCollection',
    'router_path' => 'islandora/object/%',
    'link_title' => 'P.T. Barnum Digital Collection Home |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-pt-barnum-digital-collectio_pt-barnum-digital-collection-home-:islandora/object/60002:PTBarnumDigitalCollection',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-remembering-wwi-contextual-_about-:node/89.
  $menu_links['menu-remembering-wwi-contextual-_about-:node/89'] = array(
    'menu_name' => 'menu-remembering-wwi-contextual-',
    'link_path' => 'node/89',
    'router_path' => 'node/%',
    'link_title' => 'About |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-remembering-wwi-contextual-_about-:node/89',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-remembering-wwi-contextual-_csl-digital-collections-:islandora/object/30002:csl.
  $menu_links['menu-remembering-wwi-contextual-_csl-digital-collections-:islandora/object/30002:csl'] = array(
    'menu_name' => 'menu-remembering-wwi-contextual-',
    'link_path' => 'islandora/object/30002:csl',
    'router_path' => 'islandora/object/%',
    'link_title' => 'CSL Digital Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-remembering-wwi-contextual-_csl-digital-collections-:islandora/object/30002:csl',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: menu-remembering-wwi-contextual-_remembering-wwi-collections-:islandora/object/30002:RWWI.
  $menu_links['menu-remembering-wwi-contextual-_remembering-wwi-collections-:islandora/object/30002:RWWI'] = array(
    'menu_name' => 'menu-remembering-wwi-contextual-',
    'link_path' => 'islandora/object/30002:RWWI',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Remembering WWI Collections |',
    'options' => array(
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-remembering-wwi-contextual-_remembering-wwi-collections-:islandora/object/30002:RWWI',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: menu-slater-memorial-museum-cont_about--:node/52.
  $menu_links['menu-slater-memorial-museum-cont_about--:node/52'] = array(
    'menu_name' => 'menu-slater-memorial-museum-cont',
    'link_path' => 'node/52',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-slater-memorial-museum-cont_about--:node/52',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-slater-memorial-museum-cont_slater-memorial-museum-collections-:islandora/object/230002:SMM001.
  $menu_links['menu-slater-memorial-museum-cont_slater-memorial-museum-collections-:islandora/object/230002:SMM001'] = array(
    'menu_name' => 'menu-slater-memorial-museum-cont',
    'link_path' => 'islandora/object/230002:SMM001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Slater Memorial Museum Collections |',
    'options' => array(
      'identifier' => 'menu-slater-memorial-museum-cont_slater-memorial-museum-collections-:islandora/object/230002:SMM001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-stonington-historical-conte_about--:node/56.
  $menu_links['menu-stonington-historical-conte_about--:node/56'] = array(
    'menu_name' => 'menu-stonington-historical-conte',
    'link_path' => 'node/56',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-stonington-historical-conte_about--:node/56',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-stonington-historical-conte_stonington-historical-society-collections-:islandora/object/240002:SHS001.
  $menu_links['menu-stonington-historical-conte_stonington-historical-society-collections-:islandora/object/240002:SHS001'] = array(
    'menu_name' => 'menu-stonington-historical-conte',
    'link_path' => 'islandora/object/240002:SHS001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Stonington Historical Society Collections |',
    'options' => array(
      'identifier' => 'menu-stonington-historical-conte_stonington-historical-society-collections-:islandora/object/240002:SHS001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-uconn-contextual-menu_about-:https://lib.uconn.edu/libraries/asc/about/.
  $menu_links['menu-uconn-contextual-menu_about-:https://lib.uconn.edu/libraries/asc/about/'] = array(
    'menu_name' => 'menu-uconn-contextual-menu',
    'link_path' => 'https://lib.uconn.edu/libraries/asc/about/',
    'router_path' => '',
    'link_title' => 'About |',
    'options' => array(
      'identifier' => 'menu-uconn-contextual-menu_about-:https://lib.uconn.edu/libraries/asc/about/',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(
        'target' => '_blank',
      ),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: menu-wadsworth-atheneum-contextu_about--:node/59.
  $menu_links['menu-wadsworth-atheneum-contextu_about--:node/59'] = array(
    'menu_name' => 'menu-wadsworth-atheneum-contextu',
    'link_path' => 'node/59',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-wadsworth-atheneum-contextu_about--:node/59',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-wadsworth-atheneum-contextu_wadsworth-atheneum-collections-:islandora/object/250002:WA001.
  $menu_links['menu-wadsworth-atheneum-contextu_wadsworth-atheneum-collections-:islandora/object/250002:WA001'] = array(
    'menu_name' => 'menu-wadsworth-atheneum-contextu',
    'link_path' => 'islandora/object/250002:WA001',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Wadsworth Atheneum Collections |',
    'options' => array(
      'identifier' => 'menu-wadsworth-atheneum-contextu_wadsworth-atheneum-collections-:islandora/object/250002:WA001',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-windham-textile-history-con_about--:node/63.
  $menu_links['menu-windham-textile-history-con_about--:node/63'] = array(
    'menu_name' => 'menu-windham-textile-history-con',
    'link_path' => 'node/63',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-windham-textile-history-con_about--:node/63',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-windham-textile-history-con_windham-textile--history-museum-collections-:islandora/object/360002:AdminJEWTM.
  $menu_links['menu-windham-textile-history-con_windham-textile--history-museum-collections-:islandora/object/360002:AdminJEWTM'] = array(
    'menu_name' => 'menu-windham-textile-history-con',
    'link_path' => 'islandora/object/360002:AdminJEWTM',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Windham Textile & History Museum Collections |',
    'options' => array(
      'identifier' => 'menu-windham-textile-history-con_windham-textile--history-museum-collections-:islandora/object/360002:AdminJEWTM',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );
  // Exported menu link: menu-woodbury-public-library-con_about--:node/71.
  $menu_links['menu-woodbury-public-library-con_about--:node/71'] = array(
    'menu_name' => 'menu-woodbury-public-library-con',
    'link_path' => 'node/71',
    'router_path' => 'node/%',
    'link_title' => 'About | ',
    'options' => array(
      'identifier' => 'menu-woodbury-public-library-con_about--:node/71',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 1,
  );
  // Exported menu link: menu-woodbury-public-library-con_woodbury-public-library-collections--:islandora/object/140065:Woodbury.
  $menu_links['menu-woodbury-public-library-con_woodbury-public-library-collections--:islandora/object/140065:Woodbury'] = array(
    'menu_name' => 'menu-woodbury-public-library-con',
    'link_path' => 'islandora/object/140065:Woodbury',
    'router_path' => 'islandora/object/%',
    'link_title' => 'Woodbury Public Library Collections | ',
    'options' => array(
      'identifier' => 'menu-woodbury-public-library-con_woodbury-public-library-collections--:islandora/object/140065:Woodbury',
      'icon' => array(
        'icon' => '',
        'wrapper' => '',
        'wrapper_class' => '',
        'position' => 'title_before',
        'title_wrapper_element' => 'span',
        'title_wrapper_class' => 'title',
        'breadcrumb' => 0,
        'title_wrapper' => 0,
      ),
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('ABC: A Barnum Companion');
  t('About');
  t('About the CTDA');
  t('About |');
  t('About | ');
  t('Avon Free Public Library Collections |');
  t('Bethel Public Library Collections |');
  t('Bibliomation');
  t('Bibliomation Collections |');
  t('Bill Memorial Library Collections |');
  t('Bridgeport History Center Collections |');
  t('C.H. Booth Collections |');
  t('CSL Digital Collections |');
  t('CSMNH Collections |');
  t('CT Landmarks Collections |');
  t('CTDA Technology |');
  t('Community Members | ');
  t('Connecticut College Collections |');
  t('Contact');
  t('Deep River Public Library Collections |');
  t('Derby Public Library Collection |');
  t('Enfield Public Library Collections |');
  t('Facebook');
  t('Fairfield Museum and History Center Collections |');
  t('HPL Collections | ');
  t('Hagaman Memorial Library Collections | ');
  t('Hartford Medical Society Collections |');
  t('Home');
  t('Home | ');
  t('Instagram');
  t('Ivoryton Library Association Collections |');
  t('Join');
  t('Kent Memorial Library Collections |');
  t('Litchfield Historical Society Collections |');
  t('Login');
  t('Lyman Allyn Art Museum Collections |');
  t('Mattatuck Museum Collections |');
  t('Mystic Arts Museum Collections |');
  t('Mystic Seaport Collections |');
  t('NBMAA Collections | ');
  t('New Haven Museum Collections | ');
  t('Norwalk Public Library Collection |');
  t('P.T. Barnum Digital Collection Home |');
  t('People of CTDA |');
  t('Remembering WWI Collections |');
  t('Root Collection');
  t('Slater Memorial Museum Collections |');
  t('Stonington Historical Society Collections |');
  t('Twitter');
  t('Wadsworth Atheneum Collections |');
  t('Website');
  t('Website |');
  t('Windham Textile & History Museum Collections |');
  t('Woodbury Public Library Collections | ');

  return $menu_links;
}
